version: '3.7'


# For Swarm.
configs:
  play_framework_config:
    file: ./conf/play-framework.conf

volumes:
  talkyard-backups:
  talkyard-uploads:
  talkyard-nginx-logs:
  talkyard-app-logs:
  talkyard-cache-data:
  talkyard-cache-logs:
  talkyard-pg10-data:
  talkyard-pg10-logs:
  talkyard-search-data:
  talkyard-search-logs:

services:
  web:
    image: debiki/talkyard-web:v0.2022.13-6d49a6e33
    # dockerfile: https://github.com/debiki/talkyard/blob/master/images/web/Dockerfile
    restart: always
    volumes:
      - talkyard-nginx-logs:/var/log/nginx/
      - talkyard-uploads:/opt/talkyard/uploads/:ro
        #networks:
      # Interpolation here doesn't work:?  ${PROXY_NET_NAME}:
      # instead:
      #proxy_net:
      #internal_net:
      #ipv4_address: ${INTERNAL_NET_WEB_IP}
    depends_on:
      - app
    # for Compose (Swarm: missing)
    ports:
      - 8080:80
    labels:
      - "traefik.docker.network=${PROXY_NET_NAME}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.enable=true"
      - "traefik.web.frontend.rule=Host:${TALKYARD_HOSTNAME}"
      - "traefik.web.port=80"
      - "traefik.web.protocol=http"
    environment:
      - CDN_PULL_KEY

  app:
    image: debiki/talkyard-app:v0.2022.13-6d49a6e33
    # dockerfile: https://github.com/debiki/talkyard/blob/master/images/app/Dockerfile.prod
    restart: always
    stdin_open: true  # otherwise Play exits
    volumes:
      - talkyard-app-logs:/var/log/talkyard/
      - talkyard-uploads:/opt/talkyard/uploads/
      - talkyard-backups:/opt/talkyard-backups/:ro
      # For Compose
      - ./conf/play-framework.conf:/opt/talkyard/app/conf/app-prod-override.conf:ro  # see [4WDKPU2] in debiki/talkyard
    # For Swarm
    configs:
      - source: play_framework_config
        target: /opt/talkyard/app/conf/app-prod-override.conf
        mode: 0400   # root user read-only
        #networks:
            #internal_net:
              #ipv4_address: ${INTERNAL_NET_APP_IP}
    depends_on:
      - cache
      - rdb
      - search
    environment:
            #- PLAY_SECRET_KEY
        #- TALKYARD_SECURE
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        #- TALKYARD_HOSTNAME
        #- BECOME_OWNER_EMAIL_ADDRESS

  cache:
    image: debiki/talkyard-cache:v0.2022.13-6d49a6e33
    # dockerfile: https://github.com/debiki/talkyard/blob/master/images/cache/Dockerfile
    restart: always
    volumes:
      - talkyard-cache-data:/data/
      - talkyard-cache-logs:/var/log/redis/
        #networks:
            #internal_net:
              #ipv4_address: ${INTERNAL_NET_CACHE_IP}
    sysctls:
      net.core.somaxconn: 511

  rdb:
    image: debiki/talkyard-rdb:v0.2022.13-6d49a6e33
    # dockerfile: https://github.com/debiki/talkyard/blob/master/images/rdb/Dockerfile
    restart: always
    volumes:
      - talkyard-pg10-data:/var/lib/postgresql/data/
      - talkyard-pg10-logs:/var/log/postgresql/
        #networks:
            #internal_net:
              #ipv4_address: ${INTERNAL_NET_RDB_IP}
    environment:
      - POSTGRES_PASSWORD

  search:
    image: debiki/talkyard-search:v0.2022.13-6d49a6e33
    # dockerfile: https://github.com/debiki/talkyard/blob/master/images/search/Dockerfile
    restart: always
    volumes:
      - talkyard-search-data:/usr/share/elasticsearch/data/
      - talkyard-search-logs:/usr/share/elasticsearch/logs/
        #networks:
        #internal_net:
        #ipv4_address: ${INTERNAL_NET_SEARCH_IP}
    environment:
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
